name: JSON Validation

on:
  pull_request:
    branches:
      - main

jobs:
  json-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install jsonlint
        run: npm install -g jsonlint

      - name: Validate JSON files
        run: |
          find . -name '*.json' -exec jsonlint -q {} \;
