name: Validate JSON

on:
  pull_request:
    paths:
      - '**/*.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate JSON files
        run: |
          # Find all modified JSON files and validate them
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.json$'); do
            echo "Validating $file"
            jq empty $file || exit 1  # jq is used to validate JSON
          done
